config/routes.rb
Rails.application.routes.draw do
  devise_for :managers
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :courses

  mount ApiRoot => ApiRoot::PREFIX

  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :courses
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :user_courses
  has_many :courses, through: :user_courses
  belongs_to :category

  validates :price, :currency, :url, :expire_day, presence: true
end

app/models/manager.rb
class Manager < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/pay_history.rb
class PayHistory < ApplicationRecord
  has_one :user_course
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :user_courses
  has_many :courses, through: :user_courses

  def gererate_token
    payload = { iss: Rails.application.class.parent_name, sub: self.id }
    JsonWebToken.encode(payload)
  end
  
end

app/models/user_course.rb
class UserCourse < ApplicationRecord
  belongs_to :user
  belongs_to :course
  belongs_to :pay_history

  scope :filter_by_user, -> (user_id) { where user_id: user_id }
  scope :filter_by_expired, -> { where("expired_time >= ?", Time.zone.now) }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  def authenticate_manager
    unless current_manager
      flash[:alert] = "Not allow!"
      redirect_to root_path
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_manager
  before_action :find_categories, only: [:index, :new, :create, :edit, :update]
  before_action :find_course, only: [:edit, :update, :destroy]

  def index
    @categories = Category.all
    @courses = if params[:category_id].present?
                 Course.includes(:category).where(category_id: params[:category_id])
               else
                Course.includes(:category).all
               end
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)

    if @course.save
      redirect_to courses_path, notice: "Create success"
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @course.update(course_params)
      redirect_to courses_path, notice: "Update success"
    else
      render :edit
    end
  end

  def destroy
    if @course.destroy
      redirect_to courses_path, notice: "Delete success"
    else
      redircet_to courses_path, notice: "Delete unsuccess"
    end
  end

  private

  def course_params
    params.require(:course).permit(:subject, :price, :currency, :launch, :url, :description, :expire_day, :category_id)
  end

  def find_categories
    @categories = Category.all
  end

  def find_course
    @course = Course.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<div class="row justify-content-md-center">
  <div class="col-4">
    <div class="card mt-5">
      <div class="card-body">
        <%= simple_form_for course do |f| %>
        
          <div class="form-inputs text-center">
            <%= f.input :subject, label: "subject" %>
          </div>

          <div class="form-inputs text-center">
            <%= f.input :price, label: "price" %>
          </div>

          <div class="form-inputs text-center">
            <%= f.input :currency, label: "currency" %>
          </div>

          <div class="form-inputs text-center">
            <%= f.input :launch, label: "launch" %>
          </div>

          <div class="form-inputs text-center">
            <%= f.input :url, label: "url" %>
          </div>

          <div class="form-inputs text-center">
            <%= f.input :description, label: "description" %>
          </div>

          <div class="form-inputs text-center">
            <%= f.input :expire_day, label: "expire_day" %>
          </div>

          <div class="form-inputs text-center">
            <%= f.input :category_id, label: "category", collection: categories, label_method: :second, value_method: :first %>
          </div>
      
            <%= f.submit class:'btn btn-success form-control', value: "Submit" %>
        <% end %>
      </div>
        <div class="card-footer text-muted">
        </div>
    </div>
  </div>
</div>

app/views/courses/_search.html.erb
<div class="form-inline md-form mt-4 mb-2 d-flex justify-content-center" >
  <%= form_tag(url, method: "get") do %>
    <%= select_tag :category_id, options_from_collection_for_select(categories, "id", "name"), class:"form-control mr-sm-2" %>
    <%= submit_tag "SELECT", class: "btn btn-outline-success btn-rounded btn-sm my-0" %>
  <% end %>
</div>

app/views/courses/edit.html.erb
<%= render partial: 'form', locals: {course: @course, categories: @categories.pluck(:id, :name)} %>

app/views/courses/index.html.erb
<h1 class="text-center">Course List</h1>

<%= render partial: 'search', locals: {url: "/courses", categories: @categories} %>
<div class="text-center">
  <%= link_to "New Course", new_course_path, class:" btn btn-success" %>
</div>

<table class="table mt-3">
  <thead>
    <tr>
      <th>ID</th>
      <th>Subject</th>
      <th>Category</th>
      <th>Price</th>
      <th>Currency</th>
      <th>Launch</th>
      <th>Url</th>
      <th>Description</th>
      <th>Expire day</th>
      <th class="user-table-control" scope="col"> </th>
    </tr>
  </thead>
  <tbody>
    <% @courses.each do |course| %>
    <tr>
      <td><%= course.id %></td>
      <td><%= course.subject %></td>
      <td><%= course.category.name %></td>
      <td><%= course.price %></td>
      <td><%= course.currency %></td>
      <td><%= course.launch %></td>
      <td><%= course.url %></td>
      <td><%= course.description %></td>
      <td><%= course.expire_day %></td>
      <td class="user-table-control">
        <%= link_to "EDIT", edit_course_path(course), class:"btn btn-info" %>
        <%= link_to "DELETE", course_path(course), data: {confirm: "Are you sure delete?" }, method: :delete, class:"btn btn-danger" %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/courses/new.html.erb
<%= render partial: 'form', locals: {course: @course, categories: @categories.pluck(:id, :name)} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SnapaskTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul class="nav">
      <% if current_manager %>
        <li class="nav-item"><%= link_to "Sign out", destroy_manager_session_path, method: :delete, class: "nav-link active" %></li>
        <li class="nav-item"><%= link_to "Courst List", courses_path, class: "nav-link active" %></li>
      <% else %>
        <li class="nav-item"><%= link_to "Login", new_manager_session_path, class: "nav-link active" %></li>
      <% end %>
    </ul>
    <% if flash[:alert] %>
      <div class="alert alert-light text-center" role="alert">
        <%= flash[:alert] %>
      </div>
    <% end %>

    <% if flash[:notice] %>
      <div class="alert alert-light text-center" role="alert">
        <%= flash[:notice] %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/managers/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/managers/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>